# Generated by Django 4.1.5 on 2023-01-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
